"""Initial tables

Revision ID: 5775d830c736
Revises: 
Create Date: 2025-06-08 14:52:09.767344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5775d830c736'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('track_name', sa.String(), nullable=False),
    sa.Column('car_model', sa.String(), nullable=False),
    sa.Column('lap_time_ms', sa.Integer(), nullable=False),
    sa.Column('lap_start_time', sa.DateTime(), nullable=True),
    sa.Column('lap_end_time', sa.DateTime(), nullable=True),
    sa.Column('lap_duration_ms', sa.Integer(), nullable=True),
    sa.Column('telemetry', sa.JSON(), nullable=True),
    sa.Column('sectors', sa.JSON(), nullable=False),
    sa.Column('fuel_left_liters', sa.Float(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('weather', sa.String(), nullable=True),
    sa.Column('track_temp', sa.Float(), nullable=True),
    sa.Column('air_temp', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('fog_percent', sa.Float(), nullable=True),
    sa.Column('cloud_percent', sa.Float(), nullable=True),
    sa.Column('screenshot_url', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laps_id'), 'laps', ['id'], unique=False)
    op.create_index(op.f('ix_laps_user_id'), 'laps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_laps_user_id'), table_name='laps')
    op.drop_index(op.f('ix_laps_id'), table_name='laps')
    op.drop_table('laps')
    # ### end Alembic commands ###
